version: '3.7'

services:
  postgres:
    container_name: bizzen
    image: postgres:latest
    environment:
      POSTGRES_DB: bizzen
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - net

volumes:
  postgres-data:

networks:
  net:
