repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.37.1
    hooks:
      - id: golangci-lint
        entry: bash -c 'golangci-lint run --fix'